server:
  port: 5000
spring:
  application:
    name: tracker
  datasource:
    url: ${DB_URI}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 60000
logging:
  level:
    org.springframework.security: TRACE

SECRETS:
  JWT_SECRET: ${JWT_SECRET}