server:
  port: 5000
spring:
  application:
    name: tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/application_tracker_db
    username: postgres
    password: PGsang!t234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 60000
logging:
  level:
    org.springframework.security: TRACE

cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    region:
      static: us-east-2
    s3:
      bucket:
        name: ${S3_BUCKET_NAME}

SECRETS:
  JWT_SECRET: ${JWT_SECRET}
